--Unitats de mesura
INSERT INTO UNITAT_MESURA VALUES ('U', 'Unitat');
INSERT INTO UNITAT_MESURA VALUES ('KG', 'Quilogram');
INSERT INTO UNITAT_MESURA VALUES ('L', 'Litre');

--Provincies
INSERT INTO PROVINCIA VALUES ('P1', 'Barcelona');
INSERT INTO PROVINCIA VALUES ('P2', 'Girona');

--Municipis
INSERT INTO MUNICIPI VALUES ('M1', 'P1', 'Sabadell');
INSERT INTO MUNICIPI VALUES ('M2', 'P1', 'Terrassa');
INSERT INTO MUNICIPI VALUES ('M3', 'P1', 'Barcelona');
INSERT INTO MUNICIPI VALUES ('M4', 'P2', 'Girona');
INSERT INTO MUNICIPI VALUES ('M5', 'P2', 'Figueres');

--Items
INSERT INTO ITEM VALUES ('P1', 's', 'Ordinador', 'Producte complet ordinador', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('P2', 's', 'Telèfon', 'Smartphone bàsic', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('P3', 's', 'Impressora', 'Impressora multifunció', 0, EMPTY_BLOB());

INSERT INTO ITEM VALUES ('C1', 'n', 'Processador', 'CPU Intel', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C2', 'n', 'Memòria RAM', '8GB DDR4', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C3', 'n', 'Disc Dur', '1TB SSD', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C4', 'n', 'Font Alimentació', '650W', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C5', 'n', 'Bateria Telèfon', 'Li-Ion 3000mAh', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C6', 'n', 'Càmera Telèfon', '12MP', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C7', 'n', 'Cartutx Tinta', 'Negre', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C8', 'n', 'Rodets Paper', 'Per impressora', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C9', 'n', 'Teclat extern', 'USB', 0, EMPTY_BLOB());
INSERT INTO ITEM VALUES ('C10', 'n', 'Ratolí extern', 'USB', 0, EMPTY_BLOB());

--Productes
INSERT INTO PRODUCTE VALUES ('P1');
INSERT INTO PRODUCTE VALUES ('P2');
INSERT INTO PRODUCTE VALUES ('P3');

--Components
INSERT INTO COMPONENT VALUES ('C1', 'FAB1', 200, 'U');
INSERT INTO COMPONENT VALUES ('C2', 'FAB2', 60, 'U');
INSERT INTO COMPONENT VALUES ('C3', 'FAB3', 90, 'U');
INSERT INTO COMPONENT VALUES ('C4', 'FAB4', 70, 'U');
INSERT INTO COMPONENT VALUES ('C5', 'FAB5', 40, 'U');
INSERT INTO COMPONENT VALUES ('C6', 'FAB6', 50, 'U');
INSERT INTO COMPONENT VALUES ('C7', 'FAB7', 30, 'U');
INSERT INTO COMPONENT VALUES ('C8', 'FAB8', 20, 'U');
INSERT INTO COMPONENT VALUES ('C9', 'FAB9', 25, 'U');
INSERT INTO COMPONENT VALUES ('C10', 'FAB10', 15, 'U');

--FORMACIO_PRODUCTE

--Formacio ordinador 
INSERT INTO FORMACIO_PRODUCTE VALUES ('P1', 'C1', 1);
INSERT INTO FORMACIO_PRODUCTE VALUES ('P1', 'C2', 2);
INSERT INTO FORMACIO_PRODUCTE VALUES ('P1', 'P2', 1);

--Producte telèfon 
INSERT INTO FORMACIO_PRODUCTE VALUES ('P2', 'C5', 1);
INSERT INTO FORMACIO_PRODUCTE VALUES ('P2', 'C6', 1);
INSERT INTO FORMACIO_PRODUCTE VALUES ('P2', 'C9', 1);

--Producte impressora
INSERT INTO FORMACIO_PRODUCTE VALUES ('P3', 'C7', 2);
INSERT INTO FORMACIO_PRODUCTE VALUES ('P3', 'C8', 1);
INSERT INTO FORMACIO_PRODUCTE VALUES ('P3', 'C10', 1);

--Proveidors
INSERT INTO PROVEIDOR VALUES ('PR1', 'CIF111', 'ProveidorA', 'Adreça 1', 'Joan', '600111111', 'M1');
INSERT INTO PROVEIDOR VALUES ('PR2', 'CIF222', 'ProveidorB', 'Adreça 2', 'Maria', '600222222', 'M2');
INSERT INTO PROVEIDOR VALUES ('PR3', 'CIF333', 'ProveidorC', 'Adreça 3', 'Pere', '600333333', 'M3');
INSERT INTO PROVEIDOR VALUES ('PR4', 'CIF444', 'ProveidorD', 'Adreça 4', 'Laura', '600444444', 'M4');
INSERT INTO PROVEIDOR VALUES ('PR5', 'CIF555', 'ProveidorE', 'Adreça 5', 'Jordi', '600555555', 'M5');
INSERT INTO PROVEIDOR VALUES ('PR6', 'CIF666', 'ProveidorF', 'Adreça 6', 'Carla', '600666666', 'M1');
INSERT INTO PROVEIDOR VALUES ('PR7', 'CIF777', 'ProveidorG', 'Adreça 7', 'Arnau', '600777777', 'M2');
INSERT INTO PROVEIDOR VALUES ('PR8', 'CIF888', 'ProveidorH', 'Adreça 8', 'Marta', '600888888', 'M3');

--Compres
INSERT INTO COMPRES VALUES ('C1', 'PR1', 210);
INSERT INTO COMPRES VALUES ('C1', 'PR2', 205);

INSERT INTO COMPRES VALUES ('C2', 'PR3', 65);
INSERT INTO COMPRES VALUES ('C2', 'PR4', 63);

INSERT INTO COMPRES VALUES ('C3', 'PR4', 95);
INSERT INTO COMPRES VALUES ('C4', 'PR5', 75);
INSERT INTO COMPRES VALUES ('C5', 'PR6', 45);
INSERT INTO COMPRES VALUES ('C6', 'PR7', 55);
INSERT INTO COMPRES VALUES ('C7', 'PR8', 35);
INSERT INTO COMPRES VALUES ('C8', 'PR1', 22);
INSERT INTO COMPRES VALUES ('C9', 'PR2', 28);
INSERT INTO COMPRES VALUES ('C9', 'PR3', 30);
INSERT INTO COMPRES VALUES ('C10', 'PR5', 18);
INSERT INTO COMPRES VALUES ('C10', 'PR6', 20);
